/* AUTO-GENERATED - ANY EDITION OF THIS FILE WILL BE OVERWRITTEN */
/* USE THE es5module.*.js FILES GENERATED BY WEBPACK.             */
/* THESES SHOULD BE REFERENCED IN YOUR BLAZOR.POLYFILL.SERVER    */
/* STARTUP OPTIONS. SEE THE DOCUMENTATION */

/*_IMPORT_ZONE_*/

(function () {

    if (window._es5Export === undefined || window._es5Export === null) {
        window._es5Export = {};
    }

/*_EXPORT_ZONE_*/
})();